# Remember to check the `override` file

include:
  # Main API
  - path: backend/docker-compose.yml
    project_directory: backend/

  # Auth MS
  - path: auth/docker-compose.yml
    project_directory: auth/

services:
  mu_fe:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - mu_main_be
