include:
  # Main API
  - path: backend/docker-compose.yml
    project_directory: backend/
  # TODO: Auth MS

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - main-api
