# Remember to check the `override` file

include:
  # Frontend
  - path: frontend/docker-compose.yml
    project_directory: frontend/

  # API Gateway
  - path: api_gateway/docker-compose.yml
    project_directory: api_gateway/

  # You should run the electron app directly instead of trying to run it in a container
  # Frontend Superuser
  #- path: mu_fe_superuser/docker-compose.yml
  #  project_directory: mu_fe_superuser/

services:
  mu_web_rp:
    image: nginx:latest
    hostname: mu_web_rp
    container_name: mu_web_rp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./mu_web_rp/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mu_web_rp/certs/certificado.crt:/etc/nginx/certs/certificado.crt:ro
      - ./mu_web_rp/certs/clave.key:/etc/nginx/certs/clave.key:ro

  mu_desktop_rp:
    image: nginx:latest
    hostname: mu_desktop_rp
    container_name: mu_desktop_rp
    ports:
      - "4000:4000"
    volumes:
      - ./mu_desktop_rp/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./mu_desktop_rp/certs/certificado.crt:/etc/nginx/certs/certificado.crt:ro
      - ./mu_desktop_rp/certs/clave.key:/etc/nginx/certs/clave.key:ro

