# Remember to check the `override` file

include:
  # Main API
  - path: backend/docker-compose.yml
    project_directory: backend/

  # API Gateway
  - path: api_gateway/docker-compose.yml
    project_directory: api_gateway/
