services:
  mu_fe_prod1:
    depends_on:
      - mu_ag
    networks:
      - private

  mu_fe_prod2:    
    depends_on:
      - mu_ag
    networks:
      - private

  mu_fe_prod3:
    depends_on:
      - mu_ag
    networks:
      - private

  mu_fe_de:
    depends_on:
      - mu_ag
    networks:
      - private

  mu_ag:    
    networks:
      - private

  # USERS MICROSERVICE
  mu_users_ms:
    networks:
      - private
  mu_users_db:
    networks:
      - private

  # GROUPS MICROSERVICE
  mu_groups_ms:
    networks:
      - private
  mu_groups_db:
    networks:
      - private

  # CATEGORIES MICROSERVICE
  mu_categories_ms:
    networks:
      - private
  mu_categories_db:
    networks:
      - private

  # EVENTS MICROSERVICE
  mu_events_ms:
    networks:
      - private
  mu_events_db:
    networks:
      - private

  # AUTH MICROSERVICE
  mu_auth_ms:
    ports: []
    networks:
      - private
  mu_auth_db:
    networks:
      - private
  mu_whitelist_db:
    networks:
      - private

  # BULK MICROSERVICE
  mu_bulk_rb:
    networks:
      - private
  mu_bulk_bkr:
    networks:
      - private
  mu_bulk_ms:
    networks:
      - private
  mu_bulk_wkr:
    networks:
      - private

  # TODO: this service shouldn't be run in production
  mu_bulk_dashboard:
    networks:
      - private

  # TODO: there should be two profiles for this service, one that depends on a single frontend (dev) and this one (prod)
  nginx-proxy:
    depends_on:
      - mu_fe_prod1
      - mu_fe_prod2
      - mu_fe_prod3
    networks:
      - public
      - private
