services:
  mu_fe_prod1:
    depends_on:
      - mu_ag_prod
    networks:
      - front_web_net

  mu_fe_prod2:    
    depends_on:
      - mu_ag_prod
    networks:
      - front_web_net

  mu_fe_prod3:
    depends_on:
      - mu_ag_prod
    networks:
      - front_web_net

  mu_fe_de:
    depends_on:
      - mu_ag_prod
    networks:
      - front_desktop_net

  mu_ag_prod:    
    networks:
      - front_web_net
      - front_desktop_net # TODO: the API Gateway should connect to the reverse proxy for the desktop, not the desktop client itself
      - mu_users_ms_net
      - mu_groups_ms_net
      - mu_events_ms_net
      - mu_auth_ms_net
      - mu_bulk_ms_net
      - mu_categories_ms_net

  # USERS MICROSERVICE
  mu_users_ms_prod:
    networks:
      - mu_users_ms_net
      - mu_users_db_net
  mu_users_db_prod:
    networks:
      - mu_users_db_net

  # GROUPS MICROSERVICE
  mu_groups_ms_prod:
    networks:
      - mu_groups_ms_net
      - mu_groups_db_net
  mu_groups_db_prod:
    networks:
      - mu_groups_db_net

  # CATEGORIES MICROSERVICE
  mu_categories_ms_prod:
    networks:
      - mu_categories_ms_net
      - mu_categories_db_net
  mu_categories_db_prod:
    networks:
      - mu_categories_db_net

  # EVENTS MICROSERVICE
  mu_events_ms_prod:
    networks:
      - mu_events_ms_net
      - mu_events_db_net
  mu_events_db_prod:
    networks:
      - mu_events_db_net

  # AUTH MICROSERVICE
  mu_auth_ms_prod:
    networks:
      - mu_auth_ms_net
      - mu_auth_db_net
      - mu_whitelist_db_net
  mu_auth_db_prod:
    networks:
      - mu_auth_db_net
  mu_whitelist_db_prod:
    networks:
      - mu_whitelist_db_net

  # BULK MICROSERVICE
  mu_bulk_rb_prod:
    networks:
      - mu_bulk_ms_net
  mu_bulk_bkr_prod:
    networks:
      - mu_bulk_ms_net
  mu_bulk_ms_prod:
    networks:
      - mu_bulk_ms_net
  mu_bulk_wkr_prod:
    networks:
      - mu_bulk_ms_net

  # TODO: there should be two profiles for this service, one that depends on a single frontend (dev) and this one (prod)
  nginx-proxy:
    depends_on:
      - mu_fe_prod1
      - mu_fe_prod2
      - mu_fe_prod3
    networks:
      - public
      - front_web_net

networks:
  public:
  front_web_net:
  front_desktop_net:
  mu_users_ms_net:
  mu_groups_ms_net:
  mu_events_ms_net:
  mu_auth_ms_net:
  mu_bulk_ms_net:
  mu_categories_ms_net:
  mu_users_db_net:
  mu_groups_db_net:
  mu_events_db_net:
  mu_auth_db_net:
  mu_whitelist_db_net:
  mu_categories_db_net: